pimcore:
    email:
        sender:
            name: 'PLEASE_CHANGE_ME'
            email: '<company_email_address>'
        return:
            name: 'PLEASE_CHANGE_ME'
            email: '<company_email_address>'

framework:
    mailer:
        transports:
            main: '%env(MAILER_DSN_MAIN)%'
            pimcore_newsletter: '%env(MAILER_DSN_NEWSLETTER)%'
