version: '3.0'
services:
    redis:
        image: redis:alpine
        container_name: pimcore-skeleton-redis

    db:
        image: mariadb:10.1
        container_name: pimcore-skeleton-mariadb
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb_large_prefix=1]
        volumes:
            - pimcore-skeleton-database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=pimcore
            - MYSQL_USER=pimcore
            - MYSQL_PASSWORD=pimcore

    adminer:
        image: adminer
        container_name: pimcore-skeleton-adminer
        restart: always
        volumes:
            - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - 2001:8080

    php:
        image: dpfaffenbauer/pimcore:PHP7.2-apache
        container_name: pimcore-skeleton-php
        volumes:
            - ~/.composer:/root/composer
            - .:/var/www/html:cached
            - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        ports:
            - 2000:80
        links:
            - db:db
            - redis:redis

    php-debug:
        image: dpfaffenbauer/pimcore:PHP7.2-apache-debug
        container_name: pimcore-skeleton-php-debug
        volumes:
            - ~/.composer:/root/composer
            - .:/var/www/html:cached
            - .docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        ports:
            - 2006:80
        links:
            - db:db
            - redis:redis

volumes:
    pimcore-skeleton-database: