version: '3.8'
services:
    redis:
        image: redis:alpine
        container_name: 'pimcore-skeleton-redis'

    db:
        image: mariadb:10.5
        container_name: 'pimcore-skeleton-mariadb'
        working_dir: '/application'
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-per-table=1]
        volumes:
            - 'pimcore-skeleton-database:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: ROOT
            MYSQL_DATABASE: pimcore
            MYSQL_USER: pimcore
            MYSQL_PASSWORD: pimcore

    adminer:
        image: adminer
        container_name: 'pimcore-skeleton-adminer'
        restart: always
        volumes:
            - '.docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/uploads.ini'
        ports:
            - '2001:8080'
        links:
            - db:db

    apache:
        image: httpd:2.4
        container_name: 'pimcore-skeleton-apache'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '.:/usr/local/apache2/htdocs:cached'
            - '.docker/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
            - '.docker/apache2/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf:ro'
            - '/etc/ssl/dev.local+4.pem:/usr/local/apache2/conf/server.crt'
            - '/etc/ssl/dev.local+4-key.pem:/usr/local/apache2/conf/server.key'
        links:
            - php
        depends_on:
            - db
            - redis

    php:
        image: pimcore/pimcore:PHP8.1-fpm
        container_name: 'pimcore-skeleton-php'
        volumes:
            - '~/.composer:/root/composer'
            - '.:/var/www/html:cached'
            - 'pimcore-skeleton-tmp-storage:/tmp:cached'
            - '.docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
        environment:
            COMPOSER_HOME: '/var/www/html'
            PHP_IDE_CONFIG: 'serverName=localhost'
        depends_on:
            - db
            - redis

    supervisord:
        image: pimcore/pimcore:PHP8.1-supervisord
        container_name: 'pimcore-skeleton-supervisord'
        volumes:
            - '.:/var/www/html:cached'
            - '.docker/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro'
        depends_on:
            - db

volumes:
    pimcore-skeleton-database:
    pimcore-skeleton-tmp-storage:
