version: '3.8'
services:
    redis:
        image: redis:alpine
        container_name: 'pimcore-skeleton-redis'

    db:
        image: mariadb:10.5
        container_name: 'pimcore-skeleton-mariadb'
        working_dir: '/application'
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1]
        volumes:
            - 'pimcore-skeleton-database:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: ROOT
            MYSQL_DATABASE: pimcore
            MYSQL_USER: pimcore
            MYSQL_PASSWORD: pimcore

    adminer:
        image: adminer
        container_name: 'pimcore-skeleton-adminer'
        restart: always
        volumes:
            - '.docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/uploads.ini'
        ports:
            - '2001:8080'
        links:
            - db:db

    php:
        image: pimcore/pimcore:PHP8.0-apache
        container_name: 'pimcore-skeleton-php'
        volumes:
            - '~/.composer:/root/composer'
            - '.:/var/www/html:cached'
            - 'pimcore-skeleton-tmp-storage:/tmp:cached'
            - '.docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
            - '.docker/apache2/ssl.conf:/etc/apache2/sites-enabled/001-ssl.conf'
            - '/etc/ssl/dev.local+4.pem:/etc/ssl/certs/dev.local+4.pem'
            - '/etc/ssl/dev.local+4-key.pem:/etc/ssl/private/dev.local+4-key.pem'
        ports:
            - '80:80'
            - '443:443'
        environment:
            COMPOSER_HOME: /var/www/html
        depends_on:
            - db

    php-debug:
        image: pimcore/pimcore:PHP8.0-apache-debug
        container_name: 'pimcore-skeleton-php-debug'
        volumes:
            - '~/.composer:/root/composer'
            - '.:/var/www/html:cached'
            - 'pimcore-skeleton-tmp-storage:/tmp:cached'
            - '.docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
            - '.docker/apache2/ssl.conf:/etc/apache2/sites-enabled/001-ssl.conf'
            - '~/.ssh/pimcore.local+4-key.pem:/etc/ssl/private/pimcore.local+4-key.pem'
            - '~/.ssh/pimcore.local+4.pem:/etc/ssl/certs/pimcore.local+4.pem'
        ports:
            - '2005:80'
            - '2006:443'
        environment:
            PHP_IDE_CONFIG: serverName=localhost
            COMPOSER_HOME: /var/www/html
        depends_on:
            - db

    supervisord:
        image: pimcore/pimcore:supervisord
        container_name: 'pimcore-skeleton-supervisord'
        volumes:
            - '.:/var/www/html:cached'
            - '.docker/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro'
        depends_on:
            - db

volumes:
    pimcore-skeleton-database:
    pimcore-skeleton-tmp-storage:
