services:

    # Asset Extension
    AppBundle\Twig\Extension\AssetExtension:
        tags:
            - { name: twig.extension }

    # String Extension
    AppBundle\Twig\Extension\StringExtension:
        tags:
            - { name: twig.extension }
