pimcore:
    properties:
        predefined:
            definitions:
                a7ecd5ae-d218-4964-9157-b7db84841769:
                    name: 'I18n: Front Page Mapping'
                    description: 'I18n: Use this property to map a custom front page.'
                    key: front_page_map
                    type: document
                    data: null
                    config: ''
                    ctype: document
                    inheritable: false
                    creationDate: 1641377637
                    modificationDate: 1641377637
