pimcore:
    documents:
        doc_types:
            definitions:
                44a1ca85-19f7-4f1d-95fb-a4fec560e517:
                    name: 'Teaser Snippet'
                    group: null
                    controller: 'ToolboxBundle\Controller\SnippetController::teaserAction'
                    template: null
                    type: snippet
                    priority: 0
                    creationDate: 1641377692
                    modificationDate: 1641377692
                    staticGeneratorEnabled: null
